server.port=8081
spring.application.name=ProductsMicroservice

#spring.kafka.producer.bootstrap-servers=[::1]:9094
spring.kafka.bootstrap-servers=localhost:9092,localhost:9094,localhost:9096
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
