server.port=0
spring.application.name=ProductsMicroservice


logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka=DEBUG

#spring.kafka.producer.bootstrap-servers=[::1]:9094
spring.kafka.bootstrap-servers=[::1]:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value.serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

